api_platform:
    title: GlobalGiving Explorer
    version: '2.0'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        pagination_items_per_page: 30
