parameters:
    default_trusted_proxies: 'private_ranges'
framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(default:default_trusted_proxies:TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']
    session: true
    serializer: true
    property_info: true
    lock: 'flock'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
