<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * @return array<string, array{    // Import name as key, description of the imported file as value
 *     path: string,               // Logical, relative or absolute path to the file
 *     type?: 'js'|'css'|'json',   // Type of the file, defaults to 'js'
 *     entrypoint?: bool,          // Whether the file is an entrypoint, for 'js' only
 * }|array{
 *     version: string,            // Version of the remote package
 *     package_specifier?: string, // Remote "package-name/path" specifier, defaults to the import name
 *     type?: 'js'|'css'|'json',
 *     entrypoint?: bool,
 * }>
 */
return [
    '@survos/js-twig/generated/fos_routes.js' => ['path' => './var/js_twig_bundle/generated/fos_routes.js'],
    'app' => ['path' => './assets/app.js', 'entrypoint' => true],
    'meili' => ['path' => './assets/meili.js', 'entrypoint' => true],
    '@symfony/stimulus-bundle' => ['path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js'],
    '@hotwired/stimulus' => ['version' => '3.2.2'],
    '@tabler/core' => ['version' => '1.5.1'],
    '@tabler/core/dist/css/tabler.min.css' => ['version' => '1.5.1', 'type' => 'css'],
    'instantsearch.js' => ['version' => '4.116.0'],
    'instantsearch.js/es/widgets' => ['version' => '4.116.0'],
    '@meilisearch/instant-meilisearch' => ['version' => '0.31.3'],
    '@tacman1123/twig-browser' => ['version' => '1.0.0'],
    '@tacman1123/twig-browser/adapters/symfony' => ['version' => '1.0.0'],
    'debug' => ['version' => '4.4.3'],
    'instantsearch.css/themes/algolia.min.css' => ['version' => '8.22.0', 'type' => 'css'],
    '@swc/helpers/esm/_object_spread.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_spread_props.js' => ['version' => '0.5.18'],
    'algoliasearch-helper' => ['version' => '3.29.3'],
    '@swc/helpers/esm/_sliced_to_array.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_to_consumable_array.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_define_property.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_extends.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_destructuring_empty.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_type_of.js' => ['version' => '0.5.18'],
    'algoliasearch-helper/types/algoliasearch.js' => ['version' => '3.29.3'],
    '@swc/helpers/esm/_instanceof.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_without_properties.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_call_super.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_class_call_check.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_create_class.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_inherits.js' => ['version' => '0.5.18'],
    '@algolia/events' => ['version' => '4.0.1'],
    'qs' => ['version' => '6.16.0'],
    'instantsearch-ui-components' => ['version' => '0.40.0'],
    'preact' => ['version' => '10.29.8'],
    'hogan.js' => ['version' => '3.0.2'],
    'htm/preact' => ['version' => '3.1.1'],
    'preact/hooks' => ['version' => '10.29.8'],
    '@swc/helpers/esm/_wrap_native_super.js' => ['version' => '0.5.18'],
    'meilisearch' => ['version' => '0.60.0'],
    '@tacman1123/twig-browser/src/compat/compileTwigBlocks.js' => ['version' => '1.0.0'],
    'ms' => ['version' => '2.1.3'],
    'side-channel' => ['version' => '1.1.1'],
    'es-define-property' => ['version' => '1.0.1'],
    'markdown-to-jsx' => ['version' => '7.7.17'],
    'htm' => ['version' => '3.1.1'],
    'es-errors/type' => ['version' => '1.3.0'],
    'object-inspect' => ['version' => '1.13.4'],
    'side-channel-list' => ['version' => '1.0.1'],
    'side-channel-map' => ['version' => '1.0.1'],
    'side-channel-weakmap' => ['version' => '1.0.2'],
    'react' => ['version' => '19.2.0'],
    'get-intrinsic' => ['version' => '1.2.5'],
    'call-bound' => ['version' => '1.0.2'],
    'es-errors' => ['version' => '1.3.0'],
    'es-errors/eval' => ['version' => '1.3.0'],
    'es-errors/range' => ['version' => '1.3.0'],
    'es-errors/ref' => ['version' => '1.3.0'],
    'es-errors/syntax' => ['version' => '1.3.0'],
    'es-errors/uri' => ['version' => '1.3.0'],
    'gopd' => ['version' => '1.2.0'],
    'has-symbols' => ['version' => '1.1.0'],
    'dunder-proto/get' => ['version' => '1.0.0'],
    'call-bind-apply-helpers/functionApply' => ['version' => '1.0.0'],
    'call-bind-apply-helpers/functionCall' => ['version' => '1.0.0'],
    'function-bind' => ['version' => '1.1.2'],
    'hasown' => ['version' => '2.0.2'],
    'call-bind' => ['version' => '1.0.8'],
    'call-bind-apply-helpers' => ['version' => '1.0.0'],
    'set-function-length' => ['version' => '1.2.2'],
    'call-bind-apply-helpers/applyBind' => ['version' => '1.0.0'],
    'define-data-property' => ['version' => '1.1.4'],
    'has-property-descriptors' => ['version' => '1.0.2'],
    'perfect-scrollbar' => ['version' => '1.5.6'],
    'perfect-scrollbar/css/perfect-scrollbar.min.css' => ['version' => '1.5.6', 'type' => 'css'],
    'datatables.net-plugins/i18n/en-GB.mjs' => ['version' => '3.0.2'],
    'datatables.net-plugins/i18n/es-ES.mjs' => ['version' => '3.0.2'],
    'datatables.net-plugins/i18n/de-DE.mjs' => ['version' => '3.0.2'],
    'datatables.net-bs5' => ['version' => '3.0.0'],
    'datatables.net' => ['version' => '3.0.0'],
    'datatables.net-bs5/css/dataTables.bootstrap5.min.css' => ['version' => '3.0.0', 'type' => 'css'],
    'datatables.net-bs5/css/dataTables.bootstrap5.css' => ['version' => '3.0.1', 'type' => 'css'],
    'datatables.net-buttons-bs5' => ['version' => '4.0.1'],
    'datatables.net-buttons' => ['version' => '4.0.1'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' => ['version' => '4.0.1', 'type' => 'css'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.css' => ['version' => '4.0.1', 'type' => 'css'],
    'datatables.net-responsive-bs5' => ['version' => '4.0.1'],
    'datatables.net-responsive' => ['version' => '4.0.1'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' => ['version' => '4.0.1', 'type' => 'css'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.css' => ['version' => '4.0.1', 'type' => 'css'],
    'datatables.net-searchbuilder-bs5' => ['version' => '2.0.0'],
    'datatables.net-searchbuilder' => ['version' => '2.0.0'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.min.css' => ['version' => '2.0.0', 'type' => 'css'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.css' => ['version' => '2.0.0', 'type' => 'css'],
    'datatables.net-select-bs5' => ['version' => '4.0.0'],
    'datatables.net-select' => ['version' => '4.0.0'],
    'datatables.net-select-bs5/css/select.bootstrap5.min.css' => ['version' => '4.0.0', 'type' => 'css'],
    'datatables.net-select-bs5/css/select.bootstrap5.css' => ['version' => '4.0.0', 'type' => 'css'],
    'datatables.net-columncontrol' => ['version' => '2.0.0'],
    'datatables.net-columncontrol-bs5' => ['version' => '2.0.0'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.min.css' => ['version' => '2.0.0', 'type' => 'css'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.css' => ['version' => '2.0.0', 'type' => 'css'],
    'stimulus-attributes' => ['version' => '1.0.2'],
    'escape-html' => ['version' => '1.0.3'],
    'dexie' => ['version' => '4.4.6'],
    'marked' => ['version' => '18.0.13'],
    '@stimulus-components/dialog' => ['version' => '1.0.1'],
    '@andypf/json-viewer' => ['version' => '2.8.0'],
    'pretty-print-json' => ['version' => '3.0.8'],
    'pretty-print-json/dist/css/pretty-print-json.min.css' => ['version' => '3.0.8', 'type' => 'css'],
    'flag-icons/css/flag-icons.min.css' => ['version' => '7.5.0', 'type' => 'css'],
    '@floating-ui/dom' => ['version' => '1.8.0'],
    '@floating-ui/core' => ['version' => '1.8.0'],
    '@floating-ui/utils' => ['version' => '0.2.12'],
    '@floating-ui/utils/dom' => ['version' => '0.2.12'],
];
